# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  AnnotationOnSeparateLine:
    active: true
    autoCorrect: true
  ArgumentListWrapping:
    active: false
    autoCorrect: true
    indentSize: 4
    maxLineLength: 120
  MultiLineIfElse:
    active: false
    autoCorrect: true
  NoBlankLineBeforeRbrace:
    active: false
    autoCorrect: true
  NoConsecutiveBlankLines:
    active: false
    autoCorrect: false
  NoEmptyFirstLineInMethodBlock:
    active: false
    autoCorrect: true
  NoLineBreakAfterElse:
    active: false
    autoCorrect: true
  NoLineBreakBeforeAssignment:
    active: false
    autoCorrect: true
  NoUnitReturn:
    active: false
    autoCorrect: true
  NoWildcardImports:
    active: false
  ParameterListWrapping:
    active: false
    autoCorrect: true
    indentSize: 8
    maxLineLength: 120
  Indentation:
    continuationIndentSize: 8


style:
  ReturnCount:
    active: false
  WildcardImport:
    active: false


console-reports:
  active: true

output-reports:
  active: true